# 遊戲標題
title = "祕密花園"

#------------------------------------------------------------------------------
#  全域設定 (Global Settings)
#------------------------------------------------------------------------------

[world_setting]
# 關於這個世界的宏觀描述
descript = "一個現代與奇幻交織的世界。"
# 遊戲中的專有名詞，幫助 LLM 更精準地生成內容
nouns = "魔法, 符文, 冒險者公會"

[variables]
# 用於追蹤關鍵事件或狀態的全域變數
has_met_king = false
power_is_on = false

#------------------------------------------------------------------------------
#  玩家設定 (Player Settings)
#------------------------------------------------------------------------------

[user_setting]
name = "艾倫"
descript = "一個對世界充滿好奇的年輕人。"
# 玩家的狀態值，value 為初始值
status = [
  { name = "health", value = 100, max = 100, min = 0 },
  { name = "mana",   value = 50,  max = 50,  min = 0 },
  { name = "money",  value = 10,  max = 9999, min = 0 }
]

#------------------------------------------------------------------------------
#  劇情節點 (Nodes)
#------------------------------------------------------------------------------

[[nodes]]
id = "wake_up"
descript = "你從柔軟的床上醒來，溫暖的陽光從窗戶灑進房間。"
# 只有 LLM 知道的隱藏資訊，用於豐富回應
hide_descript = "這是一個位於二樓的房間，窗外是寧靜的街道。"
# 給 LLM 的場景氛圍提示
atmosphere = "溫馨, 平靜, 安全"

# 此場景中的物品
objects = [
  { name = "書桌", detail = "一張木製書桌，上面放著幾本書。", location = "房間的角落" },
  { name = "筆記本", detail = "一本看起來很舊的皮質筆記本。", location = "書桌的抽屜裡", properties = { takable = true } }
]

# 節點轉移的條件
next = [
  { condition = { event = "action", detail = "走出房門" }, goto = "kitchen" },
  { condition = { event = "action", detail = "跳出窗戶" }, goto = "dead_end_fall" }
]

# 節點內的特殊事件觸發器
triggers = {}

max_turn = 10
when_max_turn = "媽媽的聲音從樓下傳來：「艾倫，快點下來吃早餐！」"

[[nodes]]
id = "kitchen"
descript = "你來到廚房，媽媽正在準備早餐，空氣中瀰漫著麵包的香氣。"
atmosphere = "溫暖, 生活氣息"

objects = [
  { name = "水果刀", detail = "一把鋒利的水果刀。", location = "在流理台上", properties = { takable = true, use_on = ["蘋果"] } },
  { name = "蘋果", detail = "一顆鮮紅的蘋果。", location = "在桌上的水果籃裡", properties = { takable = true } }
]

next = [
  { condition = { event = "talk", detail = "和媽媽說話" }, goto = "breakfast_dialogue" }
]

triggers = { on_enter = "媽媽微笑著跟你打招呼：「親愛的，你醒啦！」" }


#------------------------------------------------------------------------------
#  角色 (Characters)
#------------------------------------------------------------------------------

[[characters]]
id = "mom"
name = "媽媽"
descript = "一位慈祥但有時有點嘮叨的母親。"
# 給 LLM 的專屬「扮演指南」，讓角色說話的風格更穩定
personality = "總是稱呼玩家為「親愛的」，關心玩家的健康，喜歡分享鄰居的八卦。"

# 角色的狀態值
status = [
  { name = "mood", value = 80, max = 100, min = -100 }
]
